import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <main className="max-w-[150rem] mx-auto">
        <Navbar />
        {children}
        <SpeedInsights/>
        <Footer />
        </main>
        <script src="https://smtpjs.com/v3/smtp.js"/>
      </body>
    </html>
  );
}
